# Generated by Django 4.0 on 2021-12-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('published_date', models.DateField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('kind', models.CharField(choices=[('charity', 'charity'), ('event', 'event')], max_length=10)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
