# Generated by Django 4.0 on 2021-12-19 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_date', models.DateField(default=datetime.date.today)),
                ('contributor_list', models.TextField()),
            ],
            options={
                'ordering': ['-contribution_date'],
            },
        ),
    ]
